server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: '/api/v1/test/v3/api-docs'
  swagger-ui:
    path: '/api/v1/test/swagger-ui'
    doc-expansion: none
    disable-swagger-default-url: true

logging:
  level:
    org.springframework: INFO
